# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jill Kahane
email: jk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Who knows what will be posted on this site... only time will tell. Likely topics: education,
  data, dinosaurs, bagels, song ideas, best spots in Cambridge and Chicago.
baseurl: ""
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jillfish822
github_username:  jill-kahane

# Build settings
markdown: kramdown
theme: minima
